# Site Settings
title: "CyberSec , Cloud and ML/AI expert"
subtitle: "Cloud | Cyber Security | DevSecOps | AI | Network Engineerig"
description: >-
  Cyber Security, Cloud & AI Engineering expert & Keynote Speaker, specializing
  in DevSecOps, Kubernetes, Cloud Architecture, Aritifical Inteligence and
  Network Security. Sharing insights on cybersecurity, cloud native
  technologies,  and modern infrastructure solutions.
url: "https://abdes.net"
baseurl: ""

# Author Details
#
# author_logo: profile.png
# temporary removig round pic
author_logo: no_logo_round.png
author: "Abdessamad EL AMRANI"
author_bio: >-
  Senior Cloud Security Engineer with expertise in cybersecurity, cloud
  architecture,  and network infrastructure. Currently working with Fortinet's
  Tiger team, focusing  on innovative security solutions and cloud-native
  technologies.
author_email: "elamrani.abdessamad@gmail.com"
author_location: "Amsterdam, The Netherlands"
author_website_url: "https://abdes.net"
#typewrite-text: "Securing the Cloud | Building the AI | Sharing Knowledge |
#  Talking to the world"
typewrite-text: "Scroll Down for Industry & Tech Updates "
#hero_cover_img: sample_cover.jpg
#hero_cover_img: cover-abde.jpg
home_background_image: main-cover1_lens.jpg

# Professional Experience
author_work_experiences:
- company_name: "Fortinet"
  company_logo: fortinet.png
  company_url: "https://fortinet.com"
  designation: "Senior Consulting Systems Engineer (Tiger Team)"
  description: >-
    Leading member of Fortinet's elite Tiger team, specializing in complex
    security architectures, cloud-native solutions, and AI/ML-driven security
    innovations. Driving technical strategy and product development while
    providing expert consultation on cybersecurity solutions.
  visibility: true
- company_name: "Palo Alto Networks"
  company_logo: paloalto.png
  company_url: "https://paloaltonetworks.com"
  designation: "Senior Escalation Engineer"
  description: >-
    Led critical escalations for enterprise security solutions, specializing in
    cloud security and network infrastructure challenges.
  visibility: true
- company_name: "Juniper Networks"
  company_logo: juniper.png
  company_url: "https://juniper.net"
  designation: "CFTS Level 3 Engineer"
  description: >-
    Handled complex network security escalations for EMEA region, focusing on
    service provider solutions and network architecture.
  visibility: true

# Navigation
urls:
- text: Home
  url: /
- text: News&Tech
  url: /blog
- text: About Abde
  url: /about
- text: Contact
  url: /contact

# Social Media Links
linkedin_username: abdessamadelamrani
github_username: abdessamad-elamrani
twitter_username: # your-twitter-handle
medium_username: # your-medium-handle

# Comments System
hyvor_talk_website_id: 476

# Analytics and Tracking
google_analytics: # your-ga-id
wakatime_username: abdessamad-elamrani

# Contact Form
formspree_email: elamrani.abdessamad@gmail.com

# Site Features Configuration
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# Blog Configuration
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed

# Exclude Files/Folders
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- README.md
- CHANGELOG.md

# Build Destination
destination: ./build
